language: c
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq debhelper fakeroot libpipeline-dev pkg-config perl
before_script:
  - autoreconf -i
script:
  - ./configure --enable-silent-rules --disable-dependency-tracking
  - make all
  - make check PROVE_OPTIONS=-j4
compiler:
  - gcc
  - clang
